# Generated by Django 4.2.7 on 2025-01-06 14:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_da',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
    ]
