# Generated by Django 4.2.7 on 2024-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
