# Generated by Django 4.2.7 on 2025-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_recaptcha_token_alter_contact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recaptcha_token',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
