# Generated by Django 4.2.7 on 2024-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Service Feature', 'verbose_name_plural': 'Service Features'},
        ),
        migrations.AddField(
            model_name='service',
            name='description_da',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_da',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_da',
            field=models.TextField(max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description_da',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='name_da',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(upload_to='services/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(help_text='Font Awesome icon class', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
