# Generated by Django 4.2.7 on 2025-01-09 09:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_servicefeature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_da',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
    ]
