# Generated by Django 4.2.7 on 2025-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, help_text='Enable or disable this service', verbose_name='Active'),
        ),
    ]
